# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow , QApplication , QPushButton , QFileDialog , QMessageBox
import sys
import mysql.connector
import nltk
nltk.download('punkt')
from nltk.tokenize import sent_tokenize

db = mysql.connector.connect(
    host="localhost" , 
    user="root",
    password = "" , 
    database = "korpus" , 
)

cursor = db.cursor(buffered=True)




class Ui(QMainWindow):
    
    theFile = []

    def popUp(self):
        msg = QMessageBox
        msg.setWindowTitle("Hint")
        msg.setText("Penambahan Berhasil")
        msg.setIcon(QMessageBox.question)



    def insertText(self):
        msg = QMessageBox()
        msg.setWindowTitle("Hint")
        msg.setText("Korpus Berhasil ditambahkan")
        msg.setStandardButtons(QMessageBox.Cancel | QMessageBox.Retry |QMessageBox.Ignore )
        x = msg.exec_()
        print("ayank")
        # global theFile
        
        # for y in theFile:
        #     with open(y,'r',encoding="utf-8") as f:
        #         lines = f.readlines()
        #         for x in lines : 
        #             wordList = x.split(' ')
        #             test_list = list(set(wordList))
                    
        #             for z in test_list:    
        #                 cursor.execute("INSERT INTO daftar_kata (id_daftar_kata,nama_kata) VALUES (%s,%s) " , ('',z))
                    
        #             cursor.execute("INSERT INTO korpus (id_korpus,konten) VALUES (%s,%s) " , ('',x))
        #             id_korpus = cursor.lastrowid
        #             sentences = sent_tokenize(x)
        #             words = x.count(" ")+1
        #             day = self.dateEdit.date().day()
        #             month = self.dateEdit.date().month()
        #             year = self.dateEdit.date().year()
        #             theDate = year,"-",day,"-",month
        #             result = "".join(str(x) for x in theDate)
        #             cursor.execute("INSERT INTO meta_data (id_meta_data,id_korpus,tanggal,sumber,penerbit,jumlah_kata,jumlah_kalimat,judul,penulis,kategori) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) " , ('',id_korpus,result,self.textEdit_4.toPlainText(),self.textEdit_5.toPlainText(),str(words),len(sentences),self.textEdit_2.toPlainText(),self.textEdit_3.toPlainText(),self.comboBox.currentText()))
        #             db.commit()
        #     self.textEdit_6.setText("")
        
                 
                
                
                
                
                
                
                # id_meta = cursor.lastrowid
                # cursor.execute("INSERT INTO korpus (id_korpus,id_teks,id_anotasi,id_meta_data,judul,penulis) VALUES (%s,%s,%s,%s,%s,%s) " , ('',id_text,1,id_meta,self.textEdit_2.toPlainText(),self.textEdit_3.toPlainText()))
                
        

    def getFile(self):
        filename = QFileDialog.getOpenFileNames(self,'Open File','' )
        self.textEdit_6.setText(str(filename[0]))
        global theFile
        theFile = filename[0]
        # with open(theFile,"r") as f:
        #     print(f.readline())
        # print(theFile)
        # for korpus in filename : 
        #     print(korpus)
        
                # print(f.readlines())
                # arr = f.readlines() 
                # judul = arr[0].partition(":")[2]
                # penulis = arr[1].partition(":")[2]
                # sumber = arr[2].partition(":")[2]
                # penerbit = arr[3].partition(":")[2]
                # tanggal = arr[4].partition(":")[2]
                # kategori = arr[5].partition(":")[2]
                # konten = arr[6].partition(":")[2]
                # insertText(konten,tanggal,penulis,sumber,penerbit,kategori,judul)

    def setupUi(self, inputWindow):
        inputWindow.setObjectName("inputWindow")
        inputWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(inputWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(180, 190, 181, 31))
        self.textEdit_2.setMaximumSize(QtCore.QSize(431, 16777215))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(430, 190, 181, 31))
        self.textEdit_3.setMaximumSize(QtCore.QSize(431, 16777215))
        self.textEdit_3.setObjectName("textEdit_3")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(180, 280, 181, 31))
        self.dateEdit.setObjectName("dateEdit")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(180, 370, 181, 31))
        self.textEdit_4.setMaximumSize(QtCore.QSize(431, 16777215))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(430, 280, 181, 31))
        self.textEdit_5.setMaximumSize(QtCore.QSize(431, 16777215))
        self.textEdit_5.setObjectName("textEdit_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget , clicked = lambda : self.insertText())
        self.pushButton.setGeometry(QtCore.QRect(330, 460, 131, 51))
        self.pushButton.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 160, 91, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(430, 160, 91, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(180, 250, 91, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(180, 340, 91, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(430, 250, 91, 31))
        self.label_6.setObjectName("label_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.getFile())
        self.pushButton_2.setGeometry(QtCore.QRect(430, 110, 181, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(430, 370, 171, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("Pilih Kategori")
        self.comboBox.addItem("Teks Narasi")
        self.comboBox.addItem("Teks Deskripsi")
        self.comboBox.addItem("Teks Eksplanasi")
        self.comboBox.addItem("Teks Eksposisi")
        self.comboBox.addItem("Teks Prosedur")
        self.comboBox.addItem("Teks Anekdot")
        self.comboBox.addItem("Teks Laporan")
        self.comboBox.addItem("Teks Berita")
        self.comboBox.addItem("Teks Normatif")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(430, 340, 91, 31))
        self.label_7.setObjectName("label_7")
        self.textEdit_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_6.setGeometry(QtCore.QRect(180, 110, 181, 31))
        self.textEdit_6.setMaximumSize(QtCore.QSize(431, 16777215))
        self.textEdit_6.setObjectName("textEdit_6")
        inputWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(inputWindow)
        self.statusbar.setObjectName("statusbar")
        inputWindow.setStatusBar(self.statusbar)

        self.retranslateUi(inputWindow)
        QtCore.QMetaObject.connectSlotsByName(inputWindow)

    def retranslateUi(self, inputWindow):
        _translate = QtCore.QCoreApplication.translate
        inputWindow.setWindowTitle(_translate("inputWindow", "MainWindow"))
        self.textEdit_2.setHtml(_translate("inputWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_3.setHtml(_translate("inputWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_4.setHtml(_translate("inputWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_5.setHtml(_translate("inputWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("inputWindow", "Simpan"))
        self.label_2.setText(_translate("inputWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Judul Korpus</span></p></body></html>"))
        self.label_3.setText(_translate("inputWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Penulis</span></p></body></html>"))
        self.label_4.setText(_translate("inputWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Tanggal</span></p></body></html>"))
        self.label_5.setText(_translate("inputWindow", "<html><head/><body><p>Sumber</p></body></html>"))
        self.label_6.setText(_translate("inputWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Penerbit</span></p></body></html>"))
        self.pushButton_2.setText(_translate("inputWindow", "Browse"))
        self.label_7.setText(_translate("inputWindow", "<html><head/><body><p>Kategori</p></body></html>"))
        self.textEdit_6.setHtml(_translate("inputWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    inputWindow = QtWidgets.QMainWindow()
    ui = Ui()
    ui.setupUi(inputWindow)
    inputWindow.show()
    sys.exit(app.exec_())
