# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow , QApplication , QPushButton , QFileDialog
import sys
from addData import Ui
import mysql.connector
from datetime import datetime
import os
import shutil

db = mysql.connector.connect(
    host="localhost" , 
    user="root",
    password = "" , 
    database = "korpus" , 
)

data = []
cursorA = db.cursor(buffered=True)
cursorB = db.cursor(buffered=True)
cursorC = db.cursor(buffered=True)
class Ringkasan(object):

    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def showText(self):

        sql = self.textEdit.toPlainText() 

        jumlah_kata_fix = 0 
        jumlah_kalimat_fix = 0 
        cursorC.execute("SELECT COUNT(*) AS hasil FROM korpus WHERE konten LIKE "+"'"+"%"+sql+"%"+"'")
        for x in cursorC:
            total = x[0]
        
        cursorA.execute("SELECT * FROM korpus WHERE konten LIKE "+"'"+"%"+sql+"%"+"'")
        for y in cursorA:
            id_korpus = y[0] 
            print(y[1])
            cursorB.execute("SELECT * FROM meta_data WHERE id_korpus = " +str(id_korpus) )
            for a in cursorB:
                jumlah_kata = a[5]
                jumlah_kalimat = a[6]
                jumlah_kata_fix += jumlah_kata
                jumlah_kalimat_fix += jumlah_kalimat
                self.label_4.setText(str(total))
                self.label_9.setText(str(jumlah_kata_fix))
                self.label_10.setText(str(jumlah_kalimat_fix))


        
        db.commit()
        
    def download(self):

        now = datetime.now()
        dt_string = now.strftime("%d-%m-%Y %H-%M-%S")
        nameFile = dt_string + ".txt"
       
        sql = self.textEdit.toPlainText() 
        file = open(nameFile,"w")


        cursorA.execute("SELECT * FROM korpus WHERE konten LIKE "+"'"+"%"+sql+"%"+"'")
        for y in cursorA:
            id_korpus = y[0] 
            cursorB.execute("SELECT * FROM meta_data WHERE id_korpus = " +str(id_korpus) )
            for a in cursorB:
                file.write("Judul : " + a[7] +"\n")
                file.write("Penulis : " + a[8] +"\n")
                file.write("Sumber : " + a[3] +"\n")
                file.write("Penerbit : " + a[4] +"\n")
                file.write("Kategori : " + a[9] +"\n")
                file.write("Tanggal : " + str(a[2]) +"\n")
                file.write("Konten : " + y[1] +"\n")
                file.write("\n")
                file.write("========================================================================== \n \n")
                jumlah_kata = a[5]
                jumlah_kalimat = a[6]
                
        self.label_9.setText(str(jumlah_kata))
        self.label_10.setText(str(jumlah_kalimat))
        
        db.commit()

        file.close()
        shutil.move(nameFile,'exported_data/')
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(843, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 140, 291, 71))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(230, 220, 221, 31))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.showText())
        self.pushButton.setGeometry(QtCore.QRect(460, 220, 101, 31))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 300, 121, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(330, 300, 121, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(350, 300, 121, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(230, 330, 121, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(230, 360, 121, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(330, 330, 121, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(330, 360, 121, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(350, 330, 121, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(350, 360, 121, 21))
        self.label_10.setObjectName("label_10")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget , clicked = lambda : self.download())
        self.pushButton_2.setGeometry(QtCore.QRect(230, 400, 101, 31))
        self.pushButton_2.setObjectName("pushButton_2")

        # self.pushButton_3.clicked.connect(self.openWindow())

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Silahkan Masukan Korpus</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Cari "))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Hasil</span></p><p><br/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">:</span></p><p><br/></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">0</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Kata</span></p><p><br/></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Kalimat</span><br/></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">:</span></p><p><br/></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">:</span></p><p><br/></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">0</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">0</span></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Unduh"))

        
        self.actionNew.setText(_translate("MainWindow", "Add New Korpus"))
        self.actionSave.setText(_translate("MainWindow", "Get Korpus"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ringkasan()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
